version: '3.8'

services:
  openresty:
    image: openresty/openresty:alpine
    ports:
      - "9080:80"  # Changed from 8080 to 9080
      - "9443:443" # Changed from 8443 to 9443
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ssl_certs:/etc/ssl:ro
      - ./public:/var/www/html
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    volumes:
      - ./public:/var/www/html
      - ssl_certs:/etc/ssl
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'aics_tms'
      MYSQL_USER: 'aics_user'
      MYSQL_PASSWORD: 'aics_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: aics_user
      PMA_PASSWORD: aics_password
    ports:
      - "9081:80" # Changed from 8081 to 9081
    depends_on:
      - mysql
    networks:
      - app-network      

volumes:
  db_data:
  ssl_certs:

networks:
  app-network:
